# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'get_data_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(618, 182)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.dump_label = QtWidgets.QLabel(self.centralwidget)
        self.dump_label.setTextFormat(QtCore.Qt.AutoText)
        self.dump_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dump_label.setObjectName("dump_label")
        self.gridLayout.addWidget(self.dump_label, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.dump_path_line = QtWidgets.QLineEdit(self.centralwidget)
        self.dump_path_line.setText("")
        self.dump_path_line.setReadOnly(False)
        self.dump_path_line.setClearButtonEnabled(True)
        self.dump_path_line.setObjectName("dump_path_line")
        self.gridLayout.addWidget(self.dump_path_line, 0, 1, 1, 1)
        self.dump_save_line = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setBold(False)
        font.setWeight(50)
        self.dump_save_line.setFont(font)
        self.dump_save_line.setToolTip("")
        self.dump_save_line.setInputMask("")
        self.dump_save_line.setText("")
        self.dump_save_line.setFrame(True)
        self.dump_save_line.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.dump_save_line.setDragEnabled(False)
        self.dump_save_line.setClearButtonEnabled(True)
        self.dump_save_line.setObjectName("dump_save_line")
        self.gridLayout.addWidget(self.dump_save_line, 1, 1, 1, 1)
        self.dump_get_Button = QtWidgets.QPushButton(self.centralwidget)
        self.dump_get_Button.setObjectName("dump_get_Button")
        self.gridLayout.addWidget(self.dump_get_Button, 2, 2, 1, 1)
        self.dump_browse_Button = QtWidgets.QPushButton(self.centralwidget)
        self.dump_browse_Button.setObjectName("dump_browse_Button")
        self.gridLayout.addWidget(self.dump_browse_Button, 0, 2, 1, 1)
        self.dump_save_Button = QtWidgets.QPushButton(self.centralwidget)
        self.dump_save_Button.setObjectName("dump_save_Button")
        self.gridLayout.addWidget(self.dump_save_Button, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.combo_dump_name = QtWidgets.QComboBox(self.centralwidget)
        self.combo_dump_name.setPlaceholderText("")
        self.combo_dump_name.setObjectName("combo_dump_name")
        self.gridLayout.addWidget(self.combo_dump_name, 2, 1, 1, 1)
        self.dump_output_txt = QtWidgets.QTextBrowser(self.centralwidget)
        self.dump_output_txt.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(False)
        font.setWeight(50)
        self.dump_output_txt.setFont(font)
        self.dump_output_txt.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dump_output_txt.setPlaceholderText("")
        self.dump_output_txt.setObjectName("dump_output_txt")
        self.gridLayout.addWidget(self.dump_output_txt, 3, 0, 2, 2)
        self.dump_exit_app_Button = QtWidgets.QPushButton(self.centralwidget)
        self.dump_exit_app_Button.setObjectName("dump_exit_app_Button")
        self.gridLayout.addWidget(self.dump_exit_app_Button, 4, 2, 1, 1)
        self.open_bin_dir_Button = QtWidgets.QPushButton(self.centralwidget)
        self.open_bin_dir_Button.setObjectName("open_bin_dir_Button")
        self.gridLayout.addWidget(self.open_bin_dir_Button, 3, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GetData"))
        self.dump_label.setText(_translate("MainWindow", "分片压缩文件路径"))
        self.label.setText(_translate("MainWindow", "bin 文件保存路径"))
        self.dump_path_line.setPlaceholderText(_translate("MainWindow", "打开分片文件存放路径，默认当前路径"))
        self.dump_save_line.setPlaceholderText(_translate("MainWindow", "设置合成后的bin文件保存路径，默认当前路径"))
        self.dump_get_Button.setText(_translate("MainWindow", "合成"))
        self.dump_browse_Button.setText(_translate("MainWindow", "浏览"))
        self.dump_save_Button.setText(_translate("MainWindow", "浏览"))
        self.label_2.setText(_translate("MainWindow", "可合成bin文件"))
        self.dump_output_txt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier New\',\'Microsoft YaHei\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dump_exit_app_Button.setText(_translate("MainWindow", "退出"))
        self.open_bin_dir_Button.setText(_translate("MainWindow", "打开bin所在文件夹"))
